<a href="https://colab.research.google.com/github/zyntonyson/Curso-introductorio-Python/blob/master/06_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The NumPy ndarray: A Multidimensional Array Object

Basado de Python for Data Analysis Wes M Chap4


One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python.Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.

Numpy CheatSheet:  

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf


http://talimi.se/p/numpy/


In [0]:
import numpy as np  # Forma convencional de exportar numpy

In [0]:


# Generamos un ndarry random
data = np.random.randn(2, 3)
data


array([[0.81649868, 1.25249914, 0.9568823 ],
       [0.32436898, 0.75040842, 1.36563997]])

In [0]:
?? np.random.randn()

An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type .

In [0]:
# Atributos de un ndarray
print(data.shape)

print(data.dtype)

(2, 3)
float64


The easiest way to create an array is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array containing
the passed data.

In [0]:
# Array vector
a=np.array([1,2,3])

print('shape:{}'.format(a.shape))
print(a, end='\n\n\n')




shape:(3,)
[1 2 3]




In [0]:
#Array tipo matriz
a2=np.array([(1,2,3),('a','b','c')])

print('shape:{}'.format(a2.shape))
print(a2,end='\n\n\n')


shape:(2, 3)
[['1' '2' '3']
 ['a' 'b' 'c']]




In [0]:
# Array desde una lista
lista=[i for i in range(15)]
a3=np.array(lista)
print('shape:{}'.format(a3.shape))
print(a3,end='\n\n\n')



shape:(15,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]




In [0]:
np.array([i for i in range(15)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
# Array lista de lista
a4=np.array([lista,lista])
print('shape:{}'.format(a4.shape))
print(a4,end='\n\n\n')



shape:(2, 15)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]




In [0]:
# La materia prima de un np tiene que ser una estructura
np.array(0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14)

ValueError: ignored

In [0]:
# Array dado un shape
a5=np.array(lista).reshape(3,5)
print('shape:{}'.format(a5.shape))
print(a5,end='\n\n\n')

Otros tipos de Arrays

In [0]:
misalto='\n\n\n'

## Array de ceros
print(np.zeros(10), end=misalto)
print(np.zeros(10).reshape(2,5), end=misalto)





In [0]:
## Array de unos

print(np.ones(16), end=misalto)
print(np.ones(16).reshape(4,2,2), end=misalto)



In [0]:
## Array vacio

print(np.empty(10), end=misalto)



In [0]:
## Identidad

print(np.identity(5),end=misalto)



In [0]:
## Rellenar un array

np.full((2,2),3)




In [0]:
np.full(4,3).reshape(2,2)

In [0]:
np.full(5,7)

In [0]:
# Range

print(np.arange(1,16).reshape(3,5))

### Arithmetic with NumPy Arrays

In [0]:
print(data+2)

In [0]:
print (data+data)

In [0]:
# Permite la suma a uno de un vector
data1=np.arange(12).reshape(3,4)
data2=np.arange(3).reshape(3,1)
data1+data2

In [0]:
data1=np.arange(12).reshape(4,3)
data2=np.arange(3).reshape(1,3)
data1+data2

In [0]:
print(data1.shape)
print(data2.shape)

In [0]:
# Mater
data1=np.arange(12).reshape(3,4)
data2=np.arange(9).reshape(3,3)
data1+data2

In [0]:
data1=np.arange(12).reshape(3,4)
data2=np.arange(12).reshape(4,3)
data1+data2

In [0]:
print(10*data)

In [0]:
print(data*data)

In [0]:
print(data-0.4*data)

In [0]:
print(1/data)

In [0]:
print(data*data>data)

### Indexing and Slicing

* Vectores

In [0]:
arr = np.arange(27)
print(arr)


In [0]:
def printt(exp, salto='\n\n'):
  print(exp,end=salto)

In [0]:
# Indexin

printt(arr[5])
  
# Cambiar elemento

arr[5]=14

printt(arr[5])

# Slicin
printt(arr[3:7])
printt(arr[3:])
printt(arr[:8])
  
  
  

* Matrices

In [0]:
arr=arr.reshape(3,9)
print(arr)

<img src="https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png" alt="drawing" align="middle" width="300"/>

In [0]:
# Indexin
printt(arr[0,2])

#Slicin

printt(arr[:2,0])  # Desde- hasta NO se incluye el límite superior
printt(arr[2,:])
printt(arr[:1,0:])
printt(arr[:2,:2])

#### Boolean indexin

* Selecting data from an array by boolean indexing always creates a copy of the data,
even if the returned array is unchanged.
* The Python keywords and and or do not work with boolean arrays.
Use & (and) and | (or) instead.


In [0]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)


In [0]:
names == 'Bob'

In [0]:
~(names == 'Bob')

In [0]:
data[names == 'Bob']

In [0]:
data[data>1]

In [0]:
data[:,0]>0

In [0]:
data[data[:,0]>0]

In [0]:
data[names == 'Bob', 2:]

In [0]:
# To select everything but 'Bob', you can either use != or negate the condition using ~:
data[~(names == 'Bob')]

In [0]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

In [0]:
data[data < 0]

In [0]:
#Setting values with boolean arrays works in a common-sense way. To set all of the negative values in data to 0 we need only do:
printt(data)
data[data < 0] = 0
printt(data)

In [0]:
# Fijando una semilla en Numpy

print(np.random.normal(0,1,3))
print(np.random.normal(0,1,3))
print(np.random.normal(0,1,3))

The data generation functions in numpy.random use a global random seed. To avoid
global state, you can use numpy.random.RandomState to create a random number
generator isolated from others:

In [0]:
np.random.seed(1234)
print(np.random.normal(0,1,3))
np.random.seed(1234)
print(np.random.normal(0,1,3))
np.random.seed(1234)
print(np.random.normal(0,1,3))


#### Fancy indexin

In [0]:
arr=np.arange(40).reshape(8,5)
arr

In [0]:
#Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays

printt(arr[[5,2,1]])

printt(arr[[-5,-2,-1]])


#Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.
printt(arr[[1, 5, 7, 2], [0, 3, 1, 2]])


#which is the rectangular region formed by selecting a subset of the matrix’s rows and columns 
# Consiste en un doble select
printt(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])


# Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array


#### Transposing Arrays

In [0]:
arr = np.arange(15).reshape((3, 5))
printt(arr)
printt(arr.T)

### Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.


In [0]:
arr = np.arange(10)
arr

In [0]:
# Raiz cuadrada por entrada
printt(np.sqrt(arr))

# Exponencial por entrada

printt(np.exp(arr).round())

<img src="https://img2018.cnblogs.com/blog/1575244/201901/1575244-20190104110528794-772383246.png" alt="drawing" align="middle" width="500"/>


<img src="https://img2018.cnblogs.com/blog/1575244/201901/1575244-20190104110534666-1972622806.png" alt="drawing" align="middle" width="500"/>



#### Mathematical and Statistical Methods

In [0]:
arr = np.random.randn(5, 4)
arr

In [0]:
# Media global
printt(arr.mean())
printt(np.mean(arr))

In [0]:
# Media por axis
printt(arr.mean(axis=0)) # por renglón
printt(arr.mean(axis=1)) #por columnas

In [0]:
# Suma
printt(arr.sum())

printt(arr.sum(axis=0))

printt(arr.sum(axis=1))

#### Sort, Unique and other set logic

In [0]:
# Ordenar
arr=np.random.randn(6)
printt(arr)
arr.sort()  # La función actúa sobre  los datos originales
printt(arr)

In [0]:
#You can sort each one-dimensional section of values in a multidimensional array inplace 
#along an axis by passing the axis number to sort:

arr=np.random.randint(1,56,25).reshape(5,5)
printt(arr)
arr.sort(1) # ordenar por renglon
printt(arr)
arr.sort(0) ## ordenar por columna
printt(arr)

In [0]:
# Valores únicos
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

### Álgebra lineal 

In [0]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [0]:
# Producto matricial variaciones
print(x.dot(y))


[[ 28.  64.]
 [ 67. 181.]]


In [0]:

print(np.dot(x,y))



[[ 28.  64.]
 [ 67. 181.]]


In [0]:
print(x@y) 

[[ 28.  64.]
 [ 67. 181.]]


In [0]:
#numpy.linalg has a standard set of matrix decompositions and things like inverse
#and determinant.

from numpy.linalg import inv




In [0]:
# Inversa
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

In [0]:
mat@inv(mat)

<img src="http://talimi.se/wp-content/uploads/2018/01/Ska%CC%88rmavbild-2018-01-02-kl.-04.29.04.png" alt="drawing" align="middle" width="300"/>
<img src="http://talimi.se/wp-content/uploads/2018/01/Ska%CC%88rmavbild-2018-01-02-kl.-04.29.57.png" alt="drawing" align="middle" width="300"/>

## Referencias

* 100 ejercicios con Numpy

  https://github.com/rougier/numpy-100